### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by raptor235** [wp-pot/gulp-wp-pot#114]
Out of nowhere started seeing memory issues when wpPot runs...

<--- Last few GCs --->

[46760:0x108008000]    20658 ms: Scavenge 1393.8 (1424.6) -> 1393.5 (1425.6) MB, 2.6 / 0.0 ms  (average mu = 0.114, current mu = 0.037) allocation failure 
[46760:0x108008000]    21347 ms: Mark-sweep 1394.1 (1425.6) -> 1393.8 (1424.6) MB, 687.6 / 0.0 ms  (average mu = 0.070, current mu = 0.021) allocation failure scavenge might not succeed
[46760:0x108008000]    21356 ms: Scavenge 1394.4 (1424.6) -> 1394.1 (1425.6) MB, 4.6 / 0.0 ms  (average mu = 0.070, current mu = 0.021) allocation failure 

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3a3f28fdbe3d]
Security context: 0x018cd549e6e9 <JSObject>
    1: makeAbs [0x18c09045421] [/Users/bartdabek/Sites/www/lawtons.test/wp-content/themes/lawtons/node_modules/glob/common.js:~203] [pc=0x3a3f290504a3](this=0x018cabf8c8f9 <Object map = 0x18cbeec7a61>,self=0x018cec3ec591 <Glob map = 0x18cbeec7ed9>,f=0x018cf0752919 <String[160]: /Users/bartdabek/Sites/www/lawtons.test/wp-content/themes/lawtons/../../plugins/s...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10096d6b6 node::Abort() (.cold.1) [/usr/local/opt/node@10/bin/node]
 2: 0x10003b8d0 node_module_register [/usr/local/opt/node@10/bin/node]
 3: 0x10003ba91 node::OnFatalError(char const*, char const*) [/usr/local/opt/node@10/bin/node]
 4: 0x100178d87 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/opt/node@10/bin/node]
 5: 0x100178d29 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/opt/node@10/bin/node]
 6: 0x10042d29c v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/opt/node@10/bin/node]
 7: 0x10042eed9 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/opt/node@10/bin/node]
 8: 0x10042c576 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/opt/node@10/bin/node]
 9: 0x10042b387 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/opt/node@10/bin/node]
10: 0x1004339ae v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/opt/node@10/bin/node]
11: 0x1004339f8 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/opt/node@10/bin/node]
12: 0x10041404f v8::internal::Factory::AllocateRawWithImmortalMap(int, v8::internal::PretenureFlag, v8::internal::Map*, v8::internal::AllocationAlignment) [/usr/local/opt/node@10/bin/node]
13: 0x100415b6e v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/opt/node@10/bin/node]
14: 0x1004ef2ce v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/opt/node@10/bin/node]
15: 0x1006345a2 v8::internal::Runtime_StringCharCodeAt(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/opt/node@10/bin/node]
16: 0x3a3f28fdbe3d 
17: 0x3a3f290504a3 
[1]    46760 abort      gulp

No idea what's going on my system hasn't changed... nothing was upgraded yet this is now failing.

**Comment by rasmusbe** [comment]
This seems to be something related to the glob dependency, might be if you include a source with a huge amount of files.
But nothing I can do here unfortunately, you could look for a solution in the glob repository.
