### ISSUE TITLE
Trying to get  JS parser to work

### ISSUE THREAD

**Issue by alanef** [wp-pot/gulp-wp-pot#195]
Hi, excuse my basic understanding of gulp.

I have been successfully generating pot files for php

`gulp.task('translatePHP', () => {
    return gulp.src(['src/**/*.php', '!src/{vendor,vendor/**}'])
        .pipe(sort())
        .pipe(wpPot({
            domain: project,
            package: project
        }))
        .on('error', gutil.log)
        .pipe(gulp.dest('src/languages/' + project + '.pot'))
        .pipe(notify({message: 'TASK: "translate" Completed! 💯', onLast: true}));
});`

but with   my attempt at JS

`gulp.task('translateJS', () => {
    return gulp.src(['src/**/*.js', '!src/{vendor,vendor/**}'])
        .pipe(sort())
        .pipe(wpPot({
            parser: 'js',
            parserOptions: {
                ecmaVersion: 6,
            },
        }))
        .on('error', gutil.log)
        .pipe(gulp.dest('src/languages/' + project + '.js.pot'))
        .pipe(notify({message: 'TASK: "translate" Completed! 💯', onLast: true}));
});`

I just get an error and no clue as what is erroring

`[08:45:51] Using gulpfile ~/projects/github.com/alanef/plugin-widget-for-eventbrite-api-project/gulpfile.js
[08:45:51] Starting 'translateJS'...
[08:45:53] error
[08:45:53] The following tasks did not complete: translateJS
`

Any help with how to investigate would be fantastic.

**Comment by rasmusbe** [comment]
I can not reproduce this error, could you make a small JS file that triggers this error. 

Since the JS environment is much messier with different standards and non-standards my guess is that something outside the parser standard is triggering this.

**Comment by alanef** [comment]
Thanks I will create a stripped down repo for you
